// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:lazynote_flutter/core/bindings/frb_generated.dart';

/// Minimal health-check API for FRB smoke integration.
String ping() => RustLib.instance.api.crateApiPing();

/// Expose core crate version through FFI.
String coreVersion() => RustLib.instance.api.crateApiCoreVersion();
