// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:lazynote_flutter/core/bindings/api.dart';
import 'package:lazynote_flutter/core/bindings/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AncestorPathResponse dco_decode_ancestor_path_response(dynamic raw);

  @protected
  AtomCreateResponse dco_decode_atom_create_response(dynamic raw);

  @protected
  AtomItemResponse dco_decode_atom_item_response(dynamic raw);

  @protected
  AtomListItem dco_decode_atom_list_item(dynamic raw);

  @protected
  AtomListResponse dco_decode_atom_list_response(dynamic raw);

  @protected
  AtomRefLocationsResponse dco_decode_atom_ref_locations_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AtomListItem dco_decode_box_autoadd_atom_list_item(dynamic raw);

  @protected
  FfiCallerContext dco_decode_box_autoadd_ffi_caller_context(dynamic raw);

  @protected
  FfiCreateAtomRequest dco_decode_box_autoadd_ffi_create_atom_request(
    dynamic raw,
  );

  @protected
  FfiScopedAtomQuery dco_decode_box_autoadd_ffi_scoped_atom_query(dynamic raw);

  @protected
  FfiTaskStatus dco_decode_box_autoadd_ffi_task_status(dynamic raw);

  @protected
  FfiViewHint dco_decode_box_autoadd_ffi_view_hint(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceInfo dco_decode_box_autoadd_workspace_info(dynamic raw);

  @protected
  WorkspaceNodeItem dco_decode_box_autoadd_workspace_node_item(dynamic raw);

  @protected
  DesignatedFolderResponse dco_decode_designated_folder_response(dynamic raw);

  @protected
  EntryActionResponse dco_decode_entry_action_response(dynamic raw);

  @protected
  EntrySearchItem dco_decode_entry_search_item(dynamic raw);

  @protected
  EntrySearchResponse dco_decode_entry_search_response(dynamic raw);

  @protected
  FfiAtomRefLocation dco_decode_ffi_atom_ref_location(dynamic raw);

  @protected
  FfiCallerContext dco_decode_ffi_caller_context(dynamic raw);

  @protected
  FfiCallerIdentity dco_decode_ffi_caller_identity(dynamic raw);

  @protected
  FfiCreateAtomRequest dco_decode_ffi_create_atom_request(dynamic raw);

  @protected
  FfiProjectionMode dco_decode_ffi_projection_mode(dynamic raw);

  @protected
  FfiScopedAtomQuery dco_decode_ffi_scoped_atom_query(dynamic raw);

  @protected
  FfiSortSpec dco_decode_ffi_sort_spec(dynamic raw);

  @protected
  FfiStatusFilterKind dco_decode_ffi_status_filter_kind(dynamic raw);

  @protected
  FfiTaskStatus dco_decode_ffi_task_status(dynamic raw);

  @protected
  FfiTimeFilterKind dco_decode_ffi_time_filter_kind(dynamic raw);

  @protected
  FfiTimeShapeFilter dco_decode_ffi_time_shape_filter(dynamic raw);

  @protected
  FfiViewHint dco_decode_ffi_view_hint(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AtomListItem> dco_decode_list_atom_list_item(dynamic raw);

  @protected
  List<EntrySearchItem> dco_decode_list_entry_search_item(dynamic raw);

  @protected
  List<FfiAtomRefLocation> dco_decode_list_ffi_atom_ref_location(dynamic raw);

  @protected
  List<FfiTaskStatus> dco_decode_list_ffi_task_status(dynamic raw);

  @protected
  List<PathSegment> dco_decode_list_path_segment(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ScopedAtomItem> dco_decode_list_scoped_atom_item(dynamic raw);

  @protected
  List<WorkspaceInfo> dco_decode_list_workspace_info(dynamic raw);

  @protected
  List<WorkspaceNodeItem> dco_decode_list_workspace_node_item(dynamic raw);

  @protected
  LogDartEventResponse dco_decode_log_dart_event_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AtomListItem? dco_decode_opt_box_autoadd_atom_list_item(dynamic raw);

  @protected
  FfiTaskStatus? dco_decode_opt_box_autoadd_ffi_task_status(dynamic raw);

  @protected
  FfiViewHint? dco_decode_opt_box_autoadd_ffi_view_hint(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceInfo? dco_decode_opt_box_autoadd_workspace_info(dynamic raw);

  @protected
  WorkspaceNodeItem? dco_decode_opt_box_autoadd_workspace_node_item(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<FfiTaskStatus>? dco_decode_opt_list_ffi_task_status(dynamic raw);

  @protected
  PathSegment dco_decode_path_segment(dynamic raw);

  @protected
  ScopedAtomItem dco_decode_scoped_atom_item(dynamic raw);

  @protected
  ScopedQueryResponse dco_decode_scoped_query_response(dynamic raw);

  @protected
  TagsListResponse dco_decode_tags_list_response(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceActionResponse dco_decode_workspace_action_response(dynamic raw);

  @protected
  WorkspaceAncestorPathResponse dco_decode_workspace_ancestor_path_response(
    dynamic raw,
  );

  @protected
  WorkspaceInfo dco_decode_workspace_info(dynamic raw);

  @protected
  WorkspaceInfoResponse dco_decode_workspace_info_response(dynamic raw);

  @protected
  WorkspaceListChildrenResponse dco_decode_workspace_list_children_response(
    dynamic raw,
  );

  @protected
  WorkspaceListResponse dco_decode_workspace_list_response(dynamic raw);

  @protected
  WorkspaceNodeItem dco_decode_workspace_node_item(dynamic raw);

  @protected
  WorkspaceNodeResponse dco_decode_workspace_node_response(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AncestorPathResponse sse_decode_ancestor_path_response(
    SseDeserializer deserializer,
  );

  @protected
  AtomCreateResponse sse_decode_atom_create_response(
    SseDeserializer deserializer,
  );

  @protected
  AtomItemResponse sse_decode_atom_item_response(SseDeserializer deserializer);

  @protected
  AtomListItem sse_decode_atom_list_item(SseDeserializer deserializer);

  @protected
  AtomListResponse sse_decode_atom_list_response(SseDeserializer deserializer);

  @protected
  AtomRefLocationsResponse sse_decode_atom_ref_locations_response(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AtomListItem sse_decode_box_autoadd_atom_list_item(
    SseDeserializer deserializer,
  );

  @protected
  FfiCallerContext sse_decode_box_autoadd_ffi_caller_context(
    SseDeserializer deserializer,
  );

  @protected
  FfiCreateAtomRequest sse_decode_box_autoadd_ffi_create_atom_request(
    SseDeserializer deserializer,
  );

  @protected
  FfiScopedAtomQuery sse_decode_box_autoadd_ffi_scoped_atom_query(
    SseDeserializer deserializer,
  );

  @protected
  FfiTaskStatus sse_decode_box_autoadd_ffi_task_status(
    SseDeserializer deserializer,
  );

  @protected
  FfiViewHint sse_decode_box_autoadd_ffi_view_hint(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceInfo sse_decode_box_autoadd_workspace_info(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceNodeItem sse_decode_box_autoadd_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  DesignatedFolderResponse sse_decode_designated_folder_response(
    SseDeserializer deserializer,
  );

  @protected
  EntryActionResponse sse_decode_entry_action_response(
    SseDeserializer deserializer,
  );

  @protected
  EntrySearchItem sse_decode_entry_search_item(SseDeserializer deserializer);

  @protected
  EntrySearchResponse sse_decode_entry_search_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiAtomRefLocation sse_decode_ffi_atom_ref_location(
    SseDeserializer deserializer,
  );

  @protected
  FfiCallerContext sse_decode_ffi_caller_context(SseDeserializer deserializer);

  @protected
  FfiCallerIdentity sse_decode_ffi_caller_identity(
    SseDeserializer deserializer,
  );

  @protected
  FfiCreateAtomRequest sse_decode_ffi_create_atom_request(
    SseDeserializer deserializer,
  );

  @protected
  FfiProjectionMode sse_decode_ffi_projection_mode(
    SseDeserializer deserializer,
  );

  @protected
  FfiScopedAtomQuery sse_decode_ffi_scoped_atom_query(
    SseDeserializer deserializer,
  );

  @protected
  FfiSortSpec sse_decode_ffi_sort_spec(SseDeserializer deserializer);

  @protected
  FfiStatusFilterKind sse_decode_ffi_status_filter_kind(
    SseDeserializer deserializer,
  );

  @protected
  FfiTaskStatus sse_decode_ffi_task_status(SseDeserializer deserializer);

  @protected
  FfiTimeFilterKind sse_decode_ffi_time_filter_kind(
    SseDeserializer deserializer,
  );

  @protected
  FfiTimeShapeFilter sse_decode_ffi_time_shape_filter(
    SseDeserializer deserializer,
  );

  @protected
  FfiViewHint sse_decode_ffi_view_hint(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AtomListItem> sse_decode_list_atom_list_item(
    SseDeserializer deserializer,
  );

  @protected
  List<EntrySearchItem> sse_decode_list_entry_search_item(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiAtomRefLocation> sse_decode_list_ffi_atom_ref_location(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiTaskStatus> sse_decode_list_ffi_task_status(
    SseDeserializer deserializer,
  );

  @protected
  List<PathSegment> sse_decode_list_path_segment(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ScopedAtomItem> sse_decode_list_scoped_atom_item(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceInfo> sse_decode_list_workspace_info(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceNodeItem> sse_decode_list_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  LogDartEventResponse sse_decode_log_dart_event_response(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AtomListItem? sse_decode_opt_box_autoadd_atom_list_item(
    SseDeserializer deserializer,
  );

  @protected
  FfiTaskStatus? sse_decode_opt_box_autoadd_ffi_task_status(
    SseDeserializer deserializer,
  );

  @protected
  FfiViewHint? sse_decode_opt_box_autoadd_ffi_view_hint(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceInfo? sse_decode_opt_box_autoadd_workspace_info(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceNodeItem? sse_decode_opt_box_autoadd_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<FfiTaskStatus>? sse_decode_opt_list_ffi_task_status(
    SseDeserializer deserializer,
  );

  @protected
  PathSegment sse_decode_path_segment(SseDeserializer deserializer);

  @protected
  ScopedAtomItem sse_decode_scoped_atom_item(SseDeserializer deserializer);

  @protected
  ScopedQueryResponse sse_decode_scoped_query_response(
    SseDeserializer deserializer,
  );

  @protected
  TagsListResponse sse_decode_tags_list_response(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceActionResponse sse_decode_workspace_action_response(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceAncestorPathResponse sse_decode_workspace_ancestor_path_response(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceInfo sse_decode_workspace_info(SseDeserializer deserializer);

  @protected
  WorkspaceInfoResponse sse_decode_workspace_info_response(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceListChildrenResponse sse_decode_workspace_list_children_response(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceListResponse sse_decode_workspace_list_response(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceNodeItem sse_decode_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceNodeResponse sse_decode_workspace_node_response(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ancestor_path_response(
    AncestorPathResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_atom_create_response(
    AtomCreateResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_atom_item_response(
    AtomItemResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_atom_list_item(AtomListItem self, SseSerializer serializer);

  @protected
  void sse_encode_atom_list_response(
    AtomListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_atom_ref_locations_response(
    AtomRefLocationsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_atom_list_item(
    AtomListItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_caller_context(
    FfiCallerContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_create_atom_request(
    FfiCreateAtomRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_scoped_atom_query(
    FfiScopedAtomQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_task_status(
    FfiTaskStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_view_hint(
    FfiViewHint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_workspace_info(
    WorkspaceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_node_item(
    WorkspaceNodeItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_designated_folder_response(
    DesignatedFolderResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_action_response(
    EntryActionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_search_item(
    EntrySearchItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_search_response(
    EntrySearchResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_atom_ref_location(
    FfiAtomRefLocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_caller_context(
    FfiCallerContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_caller_identity(
    FfiCallerIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_create_atom_request(
    FfiCreateAtomRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_projection_mode(
    FfiProjectionMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_scoped_atom_query(
    FfiScopedAtomQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_sort_spec(FfiSortSpec self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_status_filter_kind(
    FfiStatusFilterKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_task_status(FfiTaskStatus self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_time_filter_kind(
    FfiTimeFilterKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_time_shape_filter(
    FfiTimeShapeFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_view_hint(FfiViewHint self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_atom_list_item(
    List<AtomListItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_search_item(
    List<EntrySearchItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_atom_ref_location(
    List<FfiAtomRefLocation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_task_status(
    List<FfiTaskStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_path_segment(
    List<PathSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scoped_atom_item(
    List<ScopedAtomItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_info(
    List<WorkspaceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_node_item(
    List<WorkspaceNodeItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_dart_event_response(
    LogDartEventResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_atom_list_item(
    AtomListItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_task_status(
    FfiTaskStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_view_hint(
    FfiViewHint? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_workspace_info(
    WorkspaceInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_workspace_node_item(
    WorkspaceNodeItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_ffi_task_status(
    List<FfiTaskStatus>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_path_segment(PathSegment self, SseSerializer serializer);

  @protected
  void sse_encode_scoped_atom_item(
    ScopedAtomItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scoped_query_response(
    ScopedQueryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tags_list_response(
    TagsListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_action_response(
    WorkspaceActionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_ancestor_path_response(
    WorkspaceAncestorPathResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_info(WorkspaceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_info_response(
    WorkspaceInfoResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_list_children_response(
    WorkspaceListChildrenResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_list_response(
    WorkspaceListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_node_item(
    WorkspaceNodeItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_node_response(
    WorkspaceNodeResponse self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
